### ISSUE TITLE
Review post: when i click "save review" i go to another "save review" page. Why? 

### ISSUE THREAD

**Issue by supernova4888** [supernova4888/munchbox#105]
![Screenshot 2021-05-16 at 14 04 25](https://user-images.githubusercontent.com/58419750/118396393-aad9bc80-b64f-11eb-85e1-64651ab118b1.png)
![Screenshot 2021-05-16 at 14 04 31](https://user-images.githubusercontent.com/58419750/118396397-ae6d4380-b64f-11eb-923d-bbaf0281b510.png)

**Comment by sailathatammana** [comment]
Fixed
