### ISSUE TITLE
Link error when clicking the "My saved recipes" icon

### ISSUE THREAD

**Issue by supernova4888** [supernova4888/munchbox#97]
![Screenshot 2021-05-14 at 19 00 54](https://user-images.githubusercontent.com/58419750/118304258-bd84b200-b4e6-11eb-9f24-c9a3edbf12d9.png)

**Comment by sailathatammana** [comment]
You need to docker down & up. 
We added code in backend as well.

**Comment by supernova4888** [comment]
> You need to do docker down & up.
> We added code in backend as well.

I did! It still doesnt work. I get a different error now.

![Screenshot 2021-05-15 at 16 42 40](https://user-images.githubusercontent.com/58419750/118365337-9dafc580-b59c-11eb-884e-1e6be320ff95.png)

**Comment by supernova4888** [comment]
fixed in the last PR
